# Generated by Django 5.0.2 on 2024-04-17 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'cuenta de usuario', 'verbose_name_plural': 'cuentas de usuario'},
        ),
    ]
