# Generated by Django 5.0.2 on 2024-05-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='', max_length=50, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(default='', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
