# Generated by Django 5.0.2 on 2024-06-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_phone_number_account_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, to='account.address', verbose_name='Direcciones'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Teléfono'),
        ),
    ]
