# Generated by Django 5.0.2 on 2024-06-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_phone_number_address_phone_account_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='account.address', verbose_name='Direcciones'),
        ),
    ]
