# Generated by Django 5.0.2 on 2024-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_address_created_at_address_default_address_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=10, verbose_name='CP'),
        ),
    ]
