# Generated by Django 5.0.2 on 2024-07-05 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_address_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Predefinida'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Acitva'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizada el'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='user_profile', verbose_name='Foto de Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
