# Generated by Django 5.0.2 on 2024-07-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_address_created_at_alter_address_default_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'perfil de usuario', 'verbose_name_plural': 'perfiles de usuario'},
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(choices=[('Puebla', 'Puebla'), ('CDMX', 'CDMX')], default='', max_length=50, verbose_name='Estado'),
        ),
    ]
