# Generated by Django 5.0.2 on 2024-07-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userprofile_options_alter_account_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(default='', max_length=50, verbose_name='Estado'),
        ),
    ]
