# Generated by Django 5.0.7 on 2024-07-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_account_addresses_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reference',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referencia'),
        ),
    ]
