# Generated by Django 5.0.7 on 2024-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_reference_address_nearby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='México', max_length=50, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='address',
            name='nearby',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=6, verbose_name='CP'),
        ),
    ]
