# Generated by Django 5.0.7 on 2024-07-16 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_address_country_alter_address_nearby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Preferida'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
