# Generated by Django 5.0.2 on 2024-04-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.FloatField(blank=True)),
                ('stock', models.IntegerField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image1', models.ImageField(blank=True, upload_to='photos/products')),
                ('image2', models.ImageField(blank=True, upload_to='photos/products')),
                ('image3', models.ImageField(blank=True, upload_to='photos/products')),
                ('image4', models.ImageField(blank=True, upload_to='photos/products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('discount', models.FloatField(blank=True)),
                ('start_by', models.DateTimeField(blank=True)),
                ('end_by', models.DateTimeField(blank=True)),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
