# Generated by Django 5.0.2 on 2024-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='data_sheet',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
