# Generated by Django 5.0.2 on 2024-04-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_image_subcategory'),
        ('store', '0004_alter_product_end_by_alter_product_start_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='category.subcategory'),
        ),
    ]
