# Generated by Django 5.0.2 on 2024-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
