# Generated by Django 5.0.2 on 2024-04-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.FloatField(blank=True, default=0.16),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
