# Generated by Django 5.0.2 on 2024-04-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_tax_alter_product_low_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.FloatField(blank=True, default=0.02),
        ),
    ]
