# Generated by Django 5.0.2 on 2024-04-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_subcategory_options'),
        ('store', '0010_stockvar_varcat_product_stockvar_variation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockvar',
            options={'verbose_name': 'existencia por variación', 'verbose_name_plural': 'existencias por variación'},
        ),
        migrations.RenameField(
            model_name='varcat',
            old_name='name',
            new_name='varcat',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='name',
            new_name='variation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockvar',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_var',
            field=models.ManyToManyField(blank=True, through='store.StockVar', to='store.variation'),
        ),
        migrations.AddField(
            model_name='stockvar',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.subcategory'),
        ),
        migrations.AlterField(
            model_name='stockvar',
            name='stock',
            field=models.IntegerField(blank=True, verbose_name='existencia'),
        ),
        migrations.AlterField(
            model_name='stockvar',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation'),
        ),
    ]
