# Generated by Django 5.0.2 on 2024-04-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_stockvar_options_rename_name_varcat_varcat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varcat',
            options={'verbose_name': 'cat variacion', 'verbose_name_plural': 'catalogo de variaciones'},
        ),
    ]
