# Generated by Django 5.0.2 on 2024-04-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_varcat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_var',
            new_name='stockv',
        ),
    ]
