# Generated by Django 5.0.2 on 2024-04-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_stock_var_product_stockv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation',
            field=models.CharField(max_length=50, verbose_name='variacion'),
        ),
    ]
