# Generated by Django 5.0.2 on 2024-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_variation_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockvar',
            options={'verbose_name': 'Existencia por variación', 'verbose_name_plural': 'Existencias por variación'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stockv',
            new_name='stockvariations',
        ),
        migrations.AddField(
            model_name='stockvar',
            name='value',
            field=models.CharField(default='', max_length=50, verbose_name='Valor de la variacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation',
            field=models.CharField(max_length=50, verbose_name='Variacion'),
        ),
    ]
