# Generated by Django 5.0.2 on 2024-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_stockvar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varcat',
            options={'verbose_name': 'Catálogo de variacion', 'verbose_name_plural': 'Catálogo de variaciones'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Línea de variacion', 'verbose_name_plural': 'Línea de variaciones'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_sheet',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Ficha técnica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='¿Descuento?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre prod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, verbose_name='Existencias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.FloatField(blank=True, default=0.02, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='varcat',
            name='varcat',
            field=models.CharField(max_length=50, verbose_name='Catálogo variación'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada el'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
