# Generated by Django 5.0.2 on 2024-06-11 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_desc_alter_category_name_and_more'),
        ('store', '0017_alter_product_low_price_alter_variation_varcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.subcategory', verbose_name='SubCategorias'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_sheet',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Ficha técnica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre prod'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, verbose_name='Existencias totales'),
        ),
        migrations.AlterField(
            model_name='stockvar',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='stockvar',
            name='stock',
            field=models.IntegerField(blank=True, verbose_name='Existencia por variación'),
        ),
        migrations.AlterField(
            model_name='stockvar',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.variation', verbose_name='Variacion'),
        ),
    ]
