# Generated by Django 5.0.2 on 2024-06-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_brand_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='stockvar',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Existencia por variación'),
        ),
    ]
