# Generated by Django 5.0.2 on 2024-07-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria de productos'},
        ),
    ]
