# Generated by Django 5.0.2 on 2026-07-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_barcode_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Es un servicio'),
        ),
    ]
