# Generated by Django 5.0.2 on 2024-04-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_image_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'subcategoria', 'verbose_name_plural': 'subcategorias'},
        ),
    ]
