# Generated by Django 5.0.2 on 2026-05-29 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_name', models.CharField(default='Principal', max_length=20, verbose_name='Caja')),
                ('status', models.CharField(choices=[('Enabled', 'Activa'), ('Disabled', 'Inactiva')], default='Activa', max_length=20, verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('amount_sales', models.FloatField(default=0, verbose_name='Total ventas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Cajero',
                'verbose_name_plural': 'Cajeros',
            },
        ),
        migrations.CreateModel(
            name='CRClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_balance', models.FloatField(verbose_name='Saldo inicial')),
                ('incomes', models.FloatField(verbose_name='Total ingresos')),
                ('outcomes', models.FloatField(verbose_name='Total salidas')),
                ('sales', models.FloatField(verbose_name='Total ventas')),
                ('taxes', models.FloatField(verbose_name='Total impuestos')),
                ('cash_balance', models.FloatField(verbose_name='Total efectivo')),
                ('card_balance', models.FloatField(verbose_name='Total tarjetas')),
                ('transfer_balance', models.FloatField(verbose_name='Total transferencias')),
                ('final_balance', models.FloatField(verbose_name='Saldo final')),
                ('status', models.CharField(choices=[('Started', 'Iniciado'), ('Closed', 'Cerrado')], default='Iniciado', max_length=15, verbose_name='Estatus')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('end_at', models.DateTimeField(auto_now=True, verbose_name='Finalizado')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
            },
        ),
        migrations.CreateModel(
            name='IncomeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.BooleanField(default=False, verbose_name='Entrada')),
                ('outcome', models.BooleanField(default=False, verbose_name='Salida')),
                ('amount', models.FloatField(verbose_name='Importe')),
                ('concept', models.CharField(max_length=50, verbose_name='Concepto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('crclosing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.crclosing', verbose_name='Corte')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entrada y Salida',
                'verbose_name_plural': 'Entradas y Salidas',
            },
        ),
    ]
