# Generated by Django 5.0.2 on 2026-05-29 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crclosing',
            name='cashregister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.cashregister', verbose_name='Caja'),
        ),
    ]
