# Generated by Django 5.0.2 on 2026-05-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_crclosing_cashregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crclosing',
            name='card_balance',
            field=models.FloatField(null=True, verbose_name='Total tarjetas'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='cash_balance',
            field=models.FloatField(null=True, verbose_name='Total efectivo'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='final_balance',
            field=models.FloatField(null=True, verbose_name='Saldo final'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='incomes',
            field=models.FloatField(null=True, verbose_name='Total ingresos'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='outcomes',
            field=models.FloatField(null=True, verbose_name='Total salidas'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='sales',
            field=models.FloatField(null=True, verbose_name='Total ventas'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='taxes',
            field=models.FloatField(null=True, verbose_name='Total impuestos'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='transfer_balance',
            field=models.FloatField(null=True, verbose_name='Total transferencias'),
        ),
    ]
