# Generated by Django 5.0.2 on 2026-06-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_crclosing_card_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crclosing',
            name='collect_balance',
            field=models.FloatField(null=True, verbose_name='Total cobranza'),
        ),
    ]
