# Generated by Django 5.0.2 on 2026-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_crclosing_collect_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='crclosing',
            name='total_cash',
            field=models.FloatField(null=True, verbose_name='Saldo efectivo'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='card_balance',
            field=models.FloatField(null=True, verbose_name='Ingresos tarjetas'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='cash_balance',
            field=models.FloatField(null=True, verbose_name='Ingresos efectivo'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='collect_balance',
            field=models.FloatField(null=True, verbose_name='Cobranza'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='outcomes',
            field=models.FloatField(null=True, verbose_name='Salidas de caja'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='sales',
            field=models.FloatField(null=True, verbose_name='Ingresos del día'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='transfer_balance',
            field=models.FloatField(null=True, verbose_name='Ingresos transferencias'),
        ),
    ]
