# Generated by Django 5.0.2 on 2026-06-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_crclosing_total_cash_alter_crclosing_card_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crclosing',
            name='card_balance',
            field=models.FloatField(default=0, null=True, verbose_name='Ingresos tarjetas'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='cash_balance',
            field=models.FloatField(default=0, null=True, verbose_name='Ingresos efectivo'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='collect_balance',
            field=models.FloatField(default=0, null=True, verbose_name='Cobranza'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='end_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Finalizo'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='final_balance',
            field=models.FloatField(default=0, null=True, verbose_name='Saldo final'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='incomes',
            field=models.FloatField(default=0, null=True, verbose_name='Total ingresos'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='initial_balance',
            field=models.FloatField(default=0, null=True, verbose_name='Saldo inicial'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='outcomes',
            field=models.FloatField(default=0, null=True, verbose_name='Salidas de caja'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='sales',
            field=models.FloatField(default=0, null=True, verbose_name='Ingresos del día'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='taxes',
            field=models.FloatField(default=0, null=True, verbose_name='Total impuestos'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='total_cash',
            field=models.FloatField(default=0, null=True, verbose_name='Saldo efectivo'),
        ),
        migrations.AlterField(
            model_name='crclosing',
            name='transfer_balance',
            field=models.FloatField(default=0, null=True, verbose_name='Ingresos transferencias'),
        ),
    ]
