# Generated by Django 5.0.2 on 2026-06-26 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0006_alter_crclosing_card_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CRClosing',
            new_name='CashCut',
        ),
        migrations.RenameField(
            model_name='incomeoutcome',
            old_name='crclosing',
            new_name='cashcut',
        ),
    ]
