# Generated by Django 5.0.2 on 2026-06-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0007_rename_crclosing_cashcut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='cr_name',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Caja'),
        ),
    ]
