# Generated by Django 5.0.2 on 2026-06-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0008_remove_cashregister_cr_name_cashregister_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcut',
            name='end_at',
            field=models.DateTimeField(verbose_name='Finalizo'),
        ),
    ]
