# Generated by Django 5.0.2 on 2026-06-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0009_alter_cashcut_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('Activa', 'Enabled'), ('Inactiva', 'Disabled')], default='Activa', max_length=20, verbose_name='Estatus'),
        ),
    ]
