# Generated by Django 5.0.2 on 2026-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0010_alter_cashregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('Activa', 'Enabled'), ('Inactiva', 'Disabled')], default='Enabled', max_length=20, verbose_name='Estatus'),
        ),
    ]
