# Generated by Django 5.0.2 on 2026-06-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0012_alter_cashregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Activa'), ('Disabled', 'Inactiva')], default='Activa', max_length=20, verbose_name='Estatus'),
        ),
    ]
