# Generated by Django 5.0.2 on 2026-06-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0013_alter_cashregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcut',
            name='end_at',
            field=models.DateTimeField(null=True, verbose_name='Finalizo'),
        ),
    ]
