# Generated by Django 5.0.2 on 2026-07-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0015_alter_cashregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Ocupada', 'Ocupada')], default='Activa', max_length=20, verbose_name='Estatus'),
        ),
    ]
