# Generated by Django 5.0.2 on 2026-07-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0016_alter_cashregister_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concept', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='treasury.cashcut', verbose_name='Corte')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Entrada y Salida',
                'verbose_name_plural': 'Entradas y Salidas',
            },
        ),
    ]
