# Generated by Django 5.0.2 on 2026-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0017_cashmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='concept',
            field=models.CharField(max_length=200, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Movimiento'),
        ),
    ]
