# Generated by Django 5.0.2 on 2026-07-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0018_alter_cashmovement_amount_alter_cashmovement_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='amount',
            field=models.FloatField(verbose_name='Monto'),
        ),
    ]
