# Generated by Django 5.0.2 on 2026-07-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0019_alter_cashmovement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('Active', 'Activa'), ('Inactive', 'Inactiva'), ('Busy', 'Ocupada')], default='Activa', max_length=20, verbose_name='Estatus'),
        ),
    ]
