# Generated by Django 5.0.2 on 2026-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0020_alter_cashregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcut',
            name='status',
            field=models.CharField(choices=[('Started', 'Iniciado'), ('Closed', 'Cerrado')], default='Started', max_length=15, verbose_name='Estatus'),
        ),
    ]
