# Generated by Django 5.0.2 on 2024-04-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='cart_id',
        ),
    ]
