# Generated by Django 5.0.2 on 2024-05-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_rename_name_cart_cart_id'),
        ('store', '0016_alter_varcat_options_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.stockvar'),
        ),
    ]
