# Generated by Django 5.0.2 on 2024-05-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0003_cartitem_variations'),
        ('store', '0016_alter_varcat_options_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.stockvar', verbose_name='Variaciones'),
        ),
    ]
