# Generated by Django 5.0.2 on 2024-06-11 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0017_alter_product_low_price_alter_variation_varcat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='Orden')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='Direccion')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='...Direccion')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('order_note', models.CharField(blank=True, max_length=100, verbose_name='Notas')),
                ('order_total', models.FloatField(verbose_name='Total')),
                ('tax', models.FloatField(verbose_name='Impuestos')),
                ('status', models.CharField(choices=[('New', 'Nueva'), ('Accepted', 'Aceptada'), ('Completed', 'Completada'), ('Cancelled', 'Cancelada')], default='Nueva', max_length=15, verbose_name='Estatus')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='Pago')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Método de Pago')),
                ('amount_paid', models.CharField(max_length=100, verbose_name='Importe')),
                ('status', models.CharField(max_length=100, verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diferenciador')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('varcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.varcat', verbose_name='Catalogo Variacion')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variation', verbose_name='Variacion')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment', verbose_name='Pago')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.payment', verbose_name='Pago'),
        ),
    ]
