# Generated by Django 5.0.2 on 2024-06-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nueva'), ('Accepted', 'Aceptada'), ('Completed', 'Completada'), ('Cancelled', 'Cancelada')], default='New', max_length=15, verbose_name='Estatus'),
        ),
    ]
