# Generated by Django 5.0.2 on 2024-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_address_line_2_alter_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=125, verbose_name='Notas'),
        ),
    ]
