# Generated by Django 5.0.2 on 2024-06-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_order_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Producto por orden', 'verbose_name_plural': 'Producto por ordenes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='MXN', max_length=4, verbose_name='Moneda'),
        ),
    ]
