# Generated by Django 5.0.2 on 2024-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderproduct_value_remove_orderproduct_varcat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Producto por orden', 'verbose_name_plural': 'Productos por orden'},
        ),
        migrations.AddField(
            model_name='order',
            name='ship_cost',
            field=models.FloatField(default=0, verbose_name='Envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_total',
            field=models.FloatField(default=0, verbose_name='Total con envío'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordenado'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
