# Generated by Django 5.0.2 on 2024-07-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_ship_total_order_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recibida', 'Nueva'), ('Pagada', 'Pagada'), ('Aceptada', 'Aceptada'), ('Enviada', 'Enviada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Nueva', max_length=15, verbose_name='Estatus'),
        ),
    ]
