# Generated by Django 5.0.2 on 2024-07-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.BooleanField(default=True, verbose_name='¿Enviar?'),
        ),
    ]
