# Generated by Django 5.0.7 on 2024-07-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_pickup_order_pickup_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='Ordenada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup',
            field=models.BooleanField(default=False, verbose_name='¿Retiro?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_instructions',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comentarios para recolección'),
        ),
    ]
