# Generated by Django 5.0.7 on 2024-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_is_ordered_alter_order_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistic_supp',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Proveedor de logística'),
        ),
    ]
