# Generated by Django 5.0.2 on 2026-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_customer_city_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pagado el'),
        ),
        migrations.AddField(
            model_name='payment',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nueva'), ('Paid', 'Pagada'), ('Allocated', 'Aceptada'), ('Sent', 'Enviada'), ('Finished', 'Completada'), ('Canceled', 'Cancelada')], default='Nueva', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completado'), ('Deferred', 'Por Cobrar'), ('Canceled', 'Cancelado')], max_length=20, verbose_name='Estatus'),
        ),
    ]
