# Generated by Django 5.0.2 on 2026-06-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_paid_at_payment_canceled_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Cash', 'Efectivo'), ('Transfer', 'Transferencia')], max_length=25, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completado'), ('Deferred', 'Por Cobrar'), ('Canceled', 'Cancelado')], max_length=25, verbose_name='Estatus'),
        ),
    ]
