# Generated by Django 5.0.2 on 2026-06-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_payment_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='collect',
            field=models.BooleanField(default=False, verbose_name='Cobranza'),
        ),
    ]
