# Generated by Django 5.0.2 on 2026-06-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_payment_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.FloatField(max_length=100, verbose_name='Importe'),
        ),
    ]
