# Generated by Django 5.0.2 on 2026-06-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_payment_paid_at_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(null=True, verbose_name='Pagado el'),
        ),
    ]
