# Generated by Django 5.0.2 on 2026-06-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_payment_canceled_at_alter_payment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pagado el'),
        ),
    ]
