# Generated by Django 5.0.2 on 2026-07-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_alter_orderproduct_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('Cash', 'Efectivo'), ('Transfer', 'Transferencia'), ('Deferred', 'Por Cobrar')], max_length=25, verbose_name='Método de Pago'),
        ),
    ]
