# Generated by Django 5.0.2 on 2026-07-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='CP'),
        ),
    ]
