# Generated by Django 5.0.2 on 2026-07-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_customer_country_customer_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nueva'), ('Paid', 'Pagada'), ('Allocated', 'Aceptada'), ('Sent', 'Enviada'), ('Finished', 'Completada'), ('Canceled', 'Cancelada')], default='New', max_length=15, verbose_name='Estatus'),
        ),
    ]
